export const oneUser = {
  cell: "",
  dob: { date: "", age: 0 },
  email: "",
  gender: "",
  id: { name: "", value: "" },
  location: {
    city: "",
    coordinates: { latitude: "", longitude: "" },
    country: "",
    postcode: "",
    state: "",
    street: { number: 0, name: "" },
    timezone: { offset: "", description: "" },
  },
  login: {
    md5: "",
    password: "",
    salt: "",
    sha1: "",
    sha256: "",
    username: "",
    uuid: "",
  },
  name: { title: "", first: "", last: "" },
  nat: "",
  phone: "",
  picture: { large: "", medium: "", thumbnail: "" },
  registered: { date: "", age: 0 },
  zoneId: 1,
};
